version: "3.9"
services:
    postgres:
        image: postgres:14.8-alpine
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        tty: true  # Colors
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - data:/data.tar 

        ports:
            - "5432:5432"
        restart: unless-stopped
    frontend:
        build:
            context: .
            dockerfile: docker/frontend/Dockerfile
        tty: true  # Colors
        volumes_from:
            - web:rw
    web:
        build:
            context: .
            dockerfile: docker/web/Dockerfile
        env_file:
            - ./.env
        command: python manage.py runserver 0.0.0.0:8000
        tty: true  # Colors
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        volumes:
            - .:/code
volumes:
    postgres_data:
    data:
